/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_di_thsapi_THSApi_THSHoldStock */

#ifndef _Included_pers_di_thsapi_THSApi_THSHoldStock
#define _Included_pers_di_thsapi_THSApi_THSHoldStock
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
